Feature/do 1394 use secrets manager for integrated api key
aligent/cdk-constructs pull request #1273
Opened 2023-12-22 05:26 UTC by crispy101

**Description of the proposed changes**  

* Introduce SecretsManager-based authentication parameter: tokenSecret - this is used for token-URL validation for both Prerender and Recache services
* Deprecate insecure parameters: tokenList and tokenUrlAssociation
* Improve code and instruction readability

**Screenshots (if applicable)**  

* 

**Other solutions considered (if any)**  

* 

**Notes to reviewers**  

🛈  When you've finished leaving feedback, please add a final comment to the PR tagging the author, letting them know that you have finished leaving feedback

2024-01-30 01:23 UTC, TheOrangePuff requested changes
A few comments :slightly_smiling_face: 

Have these files had prettier run over them? Some of the formatting looks a bit off :thinking:

2024-02-07 02:45 UTC, crispy101 reviewed
Thanks @TheOrangePuff for the inputs. I've made some changes.

2024-02-07 02:45 UTC, crispy101 commented on packages/prerender-fargate/README.md
> +- A pre-configured AWS SecretsManager Secret name with the value being in the format of `Map<String: String[]>`, for example, `{"token1": "https://www.example1.com,https://www.mydomain1.com", "token2
Good idea! Added a screenshot.

2024-02-07 02:45 UTC, crispy101 commented on packages/prerender-fargate/README.md
> +- Whether to enable the [VPC endpoint](https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html) for S3. Default: "false"
Nice finding. Done.

2024-02-07 02:54 UTC, TheOrangePuff commented on packages/prerender-fargate/lib/prerender/server.js
> +                    s3.getObject({
Repeated logic isn't the only reason to pull something out into a function. 

Having so much nesting makes it hard to read. A cacheObject function makes it clear that you're getting the file from s3 and then caching it.

2024-02-07 23:07 UTC, crispy101 commented on packages/prerender-fargate/lib/prerender/server.js
> +                    s3.getObject({
Roger that. Updated.

2024-02-08 04:25 UTC, TheOrangePuff approved these changes

2024-02-09 04:25 UTC, merged